### PR TITLE
Add window rect commands

### PR DESCRIPTION
**Pull request by andreastt**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/webdriver-rust/83)

### CODE REVIEW

**Comment by andreastt** [comment]
cc @AutomatedTester

**Comment by jgraham** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/command.rs, line 134 at r1](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83#-KfvdfhqwgMQQunbFxIB:-KfvdfhrCX__E536UT7k:bh9h5t7) ([raw file](https://github.com/mozilla/webdriver-rust/blob/80267b6f54a33e86716c136270edd5e2710ce6c5/src/command.rs#L134)):*
> ```Rust
>                 WebDriverCommand::SetTimeouts(parameters)
>             },
>             Route::GetWindowRect | Route::GetWindowPosition | Route::GetWindowSize => WebDriverCommand::GetWindowRect,
> ```

What's the blocker to removing the old endpoints here? At least file an issue for that.

---

*[src/command.rs, line 597 at r1](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83#-Kfvf-pea9shnIEXUpIE:-Kfvf-pea9shnIEXUpIF:bmho5ho) ([raw file](https://github.com/mozilla/webdriver-rust/blob/80267b6f54a33e86716c136270edd5e2710ce6c5/src/command.rs#L597)):*
> ```Rust
>                                  ErrorStatus::InvalidArgument,
>                                  "'x' is not an integer"))
>                                .clone())
> ```

Integers are `Copy` so there's no need to clone anything here.

---

*[src/command.rs, line 598 at r1](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83#-KfveoIyXISlI6_ngZpF:-KfveoIzPyaswGV0LwMz:b-79hvq3) ([raw file](https://github.com/mozilla/webdriver-rust/blob/80267b6f54a33e86716c136270edd5e2710ce6c5/src/command.rs#L598)):*
> ```Rust
>                                  "'x' is not an integer"))
>                                .clone())
>                 })?
> ```

So far we haven't used `?` in this library.

---

*[src/command.rs, line 1700 at r1](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83#-KfvfVBRgeko7wqMFRPJ:-KfvfVBRgeko7wqMFRPK:bhlv84l) ([raw file](https://github.com/mozilla/webdriver-rust/blob/80267b6f54a33e86716c136270edd5e2710ce6c5/src/command.rs#L1700)):*
> ```Rust
> #[cfg(test)]
> mod tests {
>     use rustc_serialize::json::Json;
> ```

OK, but I'd like to see some web-platform-tests too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83)*

**Comment by andreastt** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/command.rs, line 134 at r1](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83#-KfvdfhqwgMQQunbFxIB:-Kg-tnueaoHzgdnS5XJ3:bevw1om) ([raw file](https://github.com/mozilla/webdriver-rust/blob/80267b6f54a33e86716c136270edd5e2710ce6c5/src/command.rs#L134)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

What's the blocker to removing the old endpoints here? At least file an issue for that.
</blockquote></details>

The issue is Selenium language bindings not yet using GetElementRect. I filed https://github.com/SeleniumHQ/selenium/issues/3710 with Selenium to track the migration.

I suggest we keep the GetWindowSize, SetWindowSize, GetWindowPosition, and SetWindowPosition endpoints until that has been resolved and a new Selenium release has been made.

---

*[src/command.rs, line 597 at r1](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83#-Kfvf-pea9shnIEXUpIE:-Kg-v1sM1KYylK2ZONXv:b-896fix) ([raw file](https://github.com/mozilla/webdriver-rust/blob/80267b6f54a33e86716c136270edd5e2710ce6c5/src/command.rs#L597)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Integers are `Copy` so there's no need to clone anything here.
</blockquote></details>

Done.

---

*[src/command.rs, line 598 at r1](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83#-KfveoIyXISlI6_ngZpF:-Kg-vFsIFl2-rJc0RFpm:bbmmlxk) ([raw file](https://github.com/mozilla/webdriver-rust/blob/80267b6f54a33e86716c136270edd5e2710ce6c5/src/command.rs#L598)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

So far we haven't used `?` in this library.
</blockquote></details>

Well I think we should, but in the interests of landing this I’ve rewritten the patch to use the try! macro.

---

*[src/command.rs, line 1700 at r1](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83#-KfvfVBRgeko7wqMFRPJ:-Kg-w1nQ8_Y6Y77RYQVv:b-x9qmpm) ([raw file](https://github.com/mozilla/webdriver-rust/blob/80267b6f54a33e86716c136270edd5e2710ce6c5/src/command.rs#L1700)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

OK, but I'd like to see some web-platform-tests too.
</blockquote></details>

https://github.com/w3c/web-platform-tests/blob/master/webdriver/contexts.py needs to be updates to use the rect commands, but I’d like to do that when geckodriver with this lands in central and is hooked up to the CI.

I’ve filed https://bugzilla.mozilla.org/show_bug.cgi?id=1350358 about this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83)*

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/webdriver-rust/83)*

**Pull request merged**
